### ISSUE TITLE
Not Working in Safari

### ISSUE THREAD

**Issue by shawndeprey** [duyetdev/copy.js#1]
This is a wonderful library, however, I am running into issues in Safari. It works in Chrome + Firefox just fine, but this is the result I get in Safari:

<img width="226" alt="screen shot 2016-03-08 at 5 16 36 pm" src="https://cloud.githubusercontent.com/assets/1618808/13621071/d638686a-e551-11e5-80f5-228de993b8d6.png">

This is the version of Safari I am using if it helps:
<img width="274" alt="screen shot 2016-03-08 at 5 17 21 pm" src="https://cloud.githubusercontent.com/assets/1618808/13621074/e09d40b4-e551-11e5-8432-06be3c51afce.png">

Does this library have any known issues in Safari currently?

**Comment by duyet** [comment]
Thanks for your issue. This library relies on both [Selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) and [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) APIs. Although copy/cut operations with execCommand aren't supported on Safari yet (including mobile), it gracefully degrades because Selection is supported. 

Sorry for about that.

**Comment by shawndeprey** [comment]
@duyetdev Thanks for the info, I figured it might be something like that. This isn't an issue with this library then, I will close this out.
